module.exports = [
  {
    groupName: "jscx-1800",
    students: [{
      "firstName": "Brander",
      "lastName": "Walliker",
      "gender": "Male",
      "phone": "261-817-1880"
    }, {
      "firstName": "Millie",
      "lastName": "Gibbe",
      "gender": "Female",
      "phone": "232-859-0795"
    }, {
      "firstName": "Goldina",
      "lastName": "Worden",
      "gender": "Female",
      "phone": "576-875-2579"
    }, {
      "firstName": "Blondell",
      "lastName": "Cortese",
      "gender": "Female",
      "phone": "203-462-9287"
    }, {
      "firstName": "Mordecai",
      "lastName": "Snodin",
      "gender": "Male",
      "phone": "474-770-6077"
    }, {
      "firstName": "Deb",
      "lastName": "Butler",
      "gender": "Female",
      "phone": "587-886-0781"
    }, {
      "firstName": "Carolann",
      "lastName": "Blanshard",
      "gender": "Female",
      "phone": "108-879-3886"
    }, {
      "firstName": "Carena",
      "lastName": "Massard",
      "gender": "Female",
      "phone": "121-401-3215"
    }, {
      "firstName": "Amalle",
      "lastName": "Scarce",
      "gender": "Female",
      "phone": "323-937-5490"
    }, {
      "firstName": "Alanson",
      "lastName": "Tardiff",
      "gender": "Male",
      "phone": "431-383-1662"
    }]
  },
  {
    groupName: "jscx-2000",
    students: [{
      "firstName": "Flss",
      "lastName": "Dibdale",
      "gender": "Female",
      "phone": "916-469-5846"
    }, {
      "firstName": "Chancey",
      "lastName": "Arber",
      "gender": "Male",
      "phone": "766-834-2594"
    }, {
      "firstName": "Roldan",
      "lastName": "Garahan",
      "gender": "Male",
      "phone": "974-514-8707"
    }, {
      "firstName": "Carce",
      "lastName": "O'Hogertie",
      "gender": "Male",
      "phone": "513-716-0555"
    }, {
      "firstName": "Silvain",
      "lastName": "Bythell",
      "gender": "Male",
      "phone": "584-912-3431"
    }, {
      "firstName": "Katie",
      "lastName": "Blaymires",
      "gender": "Female",
      "phone": "105-291-8132"
    }, {
      "firstName": "Cornell",
      "lastName": "McCrainor",
      "gender": "Male",
      "phone": "357-418-3788"
    }, {
      "firstName": "Thea",
      "lastName": "De Gregoli",
      "gender": "Female",
      "phone": "849-132-0921"
    }, {
      "firstName": "Kellyann",
      "lastName": "MacNeachtain",
      "gender": "Female",
      "phone": "712-557-1817"
    }, {
      "firstName": "Aylmer",
      "lastName": "Clementet",
      "gender": "Male",
      "phone": "528-108-6631"
    }]
  }
]
